- hosts: all
  remote_user: vagrant
  become: yes
  tasks:

    - name: Terraform
      apt:
        name: terraform
        state: present
    - name: Ajustando o Timezone do Servidor
      timezone:
        name: America/Sao_Paulo
    - name: Download Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/0.12.12/terraform_0.12.12_linux_amd64.zip
        dest: /tmp/terraform_0.12.12_linux_amd64.zip    


##https://releases.hashicorp.com/terraform/0.12.12/terraform_0.12.12_linux_amd64.zip
