Vagrant.configure("2") do |config|

config.vm.box = "ubuntu/bionic64"
  config.vm.define "terraform" do |terraform|
    terraform.vm.hostname = "terraform"
    terraform.vm.provision :ansible_local do |terraforminstall|
      terraforminstall.install_mode = "default"
      terraforminstall.playbook = "playbook.yml"
      terraforminstall.verbose = true
      terraforminstall.install = true
      terraforminstall.limit = "all"
    end
    terraform.vm.provider "virtualbox" do |terraformconf|
      terraformconf.name = "terraform"
      terraformconf.memory = 1024
      terraformconf.cpus = 2
    end
  end
end
