- hosts: all
  remote_user: vagrant
  become: yes
  tasks:

    - name: Instalando Ansible para provider Cloud
      apt:
        name: ansible
        state: present
    - name: Ajustando o Timezone do Servidor
      timezone:
        name: America/Sao_Paulo

