Vagrant.configure("2") do |config|

config.vm.box = "ubuntu/bionic64"
  config.vm.define "ansible" do |ansible|
    ansible.vm.hostname = "ansible"
    ansible.vm.provision :ansible_local do |ansibleinstall|
      ansibleinstall.install_mode = "default"
      ansibleinstall.playbook = "playbook.yml"
      ansibleinstall.verbose = true
      ansibleinstall.install = true
      ansibleinstall.limit = "all"
    end
    ansible.vm.provider "virtualbox" do |ansibleconf|
      ansibleconf.name = "ansible"
      ansibleconf.memory = 1024
      ansibleconf.cpus = 2
    end
  end
end
